name: Makefile CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: init
      run: python -m venv venv

    - name: install
      run: pip install -r requirements.txt

    - name: activate
      run: . venv/bin/activate

    - name: run
      run: make
